require 'minitest/autorun'
require 'minitest/unit'

# files to test
require 'the_truth'
require 'reverse'
require 'hello_world'
require 'maximum'
require 'nil_values'
require 'map'
require 'fizz_buzz'
require 'mis_mtd'
require 'black_jack'
require 'mis_mtd_two'
require 'temperature_bot'
require 'injected_and_rejected'
